### ISSUE TITLE
uglifyjs on windows

### ISSUE THREAD

**Issue by Pablushka** [markstory/asset_compress#231]
I have some problems running uglifyjs in my windows machine (Win 7 Utimate 32bits) and assets_compress. The error is the following:

    PS D:\wamp\www\mysite> .\Console\cake AssetCompress.AssetCompress build
    
    
    Welcome to CakePHP v2.6.0 Console
    ---------------------------------------------------------------
    App : mysite
    Path: D:\wamp\www\mysite\
    ---------------------------------------------------------------
    
    Building files defined in the ini file
    ---------------------------------------------------------------
    Saving file for libs.js
    Error: C:\Users\Pablushka\AppData\Roaming\npm\uglifyjs:2
    basedir=`dirname "$0"`
            ^
    SyntaxError: Unexpected token ILLEGAL
        at Module._compile (module.js:439:25)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:906:3
    Skip building all.css existing file is still fresh.
    
    Building files in views
    ---------------------------------------------------------------

Running uglifyjs in command line (I'm using powershell) just run fine: 

    PS D:\wamp\www\mysite\webroot\js> uglifyjs -o .\modal.min.js .\modal.js

I get the correct compressed modal.min.js as spected, so I believe node and uglify are installed properly.

My asset_compress.ini file looks this way:

    [General]
    cacheConfig = false
    alwaysEnableController = false
    
    [js]
    ;baseUrl = http://cdn.example.com
    timestamp = false
    paths[] = WEBROOT/js/*
    cachePath = WEBROOT/cache_js
    ;filters[] = Sprockets
    ;filters[] = YuiJs
    filters[] = UglifyJs
    
    [filter_UglifyJs]
    node = C:\Program Files\nodejs\node.exe
    node_path = node_modules\uglify-js\bin
    uglify = C:\Users\Pablushka\AppData\Roaming\npm\uglifyjs
    
    [filter_CssMinFilter]
    path = natxet/CssMin/src/CssMin.php
    
    [libs.js]
    files[] = jquery.js
    files[] = jquery.easing.1.3.js
    files[] = jquery.equalheights.js
    files[] = jquery.isotope.min.js
    files[] = jquery.mobile.customized.min.js
    files[] = jquery.mobilemenu.js
    files[] = jquery.ui.totop.js
    files[] = jquery-migrate-1.2.1.min.js
    files[] = touchTouch.jquery.js
    files[] = bootstrap.min.js
    files[] = bootstrap-filestyle.js
    files[] = camera.js
    files[] = html5shiv.js
    files[] = modal.js
    files[] = superfish.js
    files[] = TMForm.js
    files[] = tm-scripts.js
    files[] = tmstickup.js
    ;filters[] = UglifyJs
    
    
    ; Create the CSS extension
    [css]
    paths[] = WEBROOT/css/*
    cachePath = WEBROOT/cache_css
    filters[] = CssMinFilter
    
    [all.css]
    files[] = touchTouch.css
    files[] = bootstrap.css
    files[] = cake.generic.css
    files[] = camera.css
    files[] = contact-form.css
    files[] = stuck.css
    files[] = style.css
    ;filters[] = CssMinFilter

I have searched and read all windows related issues here without success. I'm sure this has been solved by another windows user. Any help will be apreciated. Thank you.

**Comment by markstory** [comment]
You need to run the `.bat` file instead I suspect.

**Comment by Pablushka** [comment]
No bat file, but a .cmd file instead. So I try this:

`uglify = C:\Users\Pablushka\AppData\Roaming\npm\uglifyjs.cmd`

and get the following output:

	PS D:\wamp\www\mysite> .\Console\cake AssetCompress.AssetCompress build
	
	
	Welcome to CakePHP v2.6.0 Console
	---------------------------------------------------------------
	App : mysite
	Path: D:\wamp\www\mysite\
	---------------------------------------------------------------
	
	Building files defined in the ini file
	---------------------------------------------------------------
	Saving file for libs.js
	Error: C:\Users\Pablushka\AppData\Roaming\npm\uglifyjs.cmd:1
	(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
	                                                              ^
	SyntaxError: Unexpected token ILLEGAL
	    at Module._compile (module.js:439:25)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:906:3
	Saving file for all.css
	
	Building files in views
	---------------------------------------------------------------

Running a simple test to check cmd file: 

	PS D:\wamp\www\mysite\webroot\js> C:\Users\Pablushka\AppData\Roaming\npm\uglifyjs.cmd -o .\modal.min.js .\modal.js

works as spected. This is freaking me out...

**Comment by markstory** [comment]
Well in the first scenario you're trying to run a `.cmd` file with node, which won't work. In the second case you're using powershell to run a `.cmd` file which is its native format. In the [uglify2 repo](https://github.com/mishoo/UglifyJS2/blob/master/bin/uglifyjs) there is a bin/uglifyjs file that contains JS. I would try running that file instead of the `.cmd` file or shell script.

**Comment by Pablushka** [comment]
Ok. Thank you very much for your work and time. Your last comment give me the solution. The correct configuration for my windows box (and may be other windows systems) is as follows:

    [filter_UglifyJs]
    node = C:\Program Files\nodejs\node.exe
    node_path = node_modules\uglify-js\bin
    uglify = C:\Users\<User Directory>\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs

where <User Directory> is my windows user home directory.

I'm sure this configuration example will be very helpfull for unexperienced users and it could be posted in the documentation to help others with a practical sample. 

I'm very happy now with the results, your work is amazing!

**Comment by markstory** [comment]
Great, I can update the wiki docs to make mention of the windows path differences.
