### ISSUE TITLE
cannot load filter in cake 3 when using bin/cake asset_compress.asset_compress build

### ISSUE THREAD

**Issue by simkimsia** [markstory/asset_compress#242]
I am using asset_compress for cake 3.

this is my composer.json

```
"markstory/asset_compress": "3.0.*-dev",
        "natxet/CssMin": "3.0.*@dev"
```

This is my asset_compress.ini

```
[filter_CssMin]
path = WEBROOT/../vendor/natxet/CssMin/src/CssMin.php

[all.css]
files[] = base.css
files[] = cake.css
files[] = bootstrap.css
filters[] = CssMin
```

I get a cannot load CssMin filter error when I try to `bin/cake asset_compress.asset_compress build`

How do I correct this?

And is there a better way to write the path for the CssMin filter?

**Comment by markstory** [comment]
You shouldn't need the path as CssMin should autoload. I can doubke check that though.

**Comment by markstory** [comment]
The CssMin filter has been renamed `CssMinFilter` for 3.x as to not conflict with `CssMin` itself.
