### ISSUE TITLE
development mode - how to setup 

### ISSUE THREAD

**Issue by phpepe** [markstory/asset_compress#243]
Hi there, I have a question for you
The documentation says that under development mode the cache is regenerated en each request. 
My question is, how can I setup my app / plugin the develpment mode ?
thanks

**Comment by markstory** [comment]
Just make sure debug>0, and that you the plugin correctly:

```php
// in your app/Config/bootstrap.php file.
CakePlugin::load('AssetCompress', array('bootstrap' => true));
```
