### ISSUE TITLE
Wrong cache path (missing slash)

### ISSUE THREAD

**Issue by Laykou** [markstory/asset_compress#247]
Hi,

after the last composer update something happened in the asset_compress or the way how CakePHP 3.0 works.

This is my **asset_compress.ini**
```INI
[General]
cacheConfig = false

[js]
cachePath = WEBROOT/cache/
timestamp = true
paths[] = WEBROOT/
paths[] = WEBROOT/js/
paths[] = WEBROOT/vendor/
paths[] = WEBROOT/vendor/js/
filters[] = JShrinkFilter

[application.js]
files[] = jQuery/jquery-1.11.0.js
# ... other files ...

[css]
cachePath = WEBROOT/cache/
timestamp = true
paths[] = WEBROOT/
paths[] = WEBROOT/css/
paths[] = WEBROOT/vendor/
paths[] = WEBROOT/vendor/css/
filters[] = \App\Lib\AssetCompress\Filter\SassFilter
filters[] = CssMinFilter

[application.css]
files[] = bootstrap/bootstrap.min.css
# ... other files ...
```

This is how I include those files in the **.ctp**:
```PHP
echo $this->AssetCompress->css('application.css');
echo $this->AssetCompress->script('application.js');
```

The path that is currently generated to the cached files is:

```
http://localhost/maple/cacheapplication.css
http://localhost/maple/cacheapplication.js
```

Obviously there is **missing slash**. Therefore the files cannot be loaded by browser.
This is on my development machine, so the `debug = true` is set in config.

I'm running on PHP 5.6, Windows 7, IIS 7.

**Comment by markstory** [comment]
It is likely a mistake in the recent changes I've been doing to the 3.0 code. I can get that fixed as the URLs should be correct.

**Comment by markstory** [comment]
I wasn't able to reproduce this on my machine. What does `$this->AssetCompress->url('application.js')` give you? It might be incorrect there, and if it is take a look inside that method and see where it is going wrong? There are some path separator checks in _getRoute(). Unfortunately I can't get my windows VM working right now as an OS upgrade broke VMWare.

**Comment by Laykou** [comment]
I've found something and created a pull-request. However the code I'm changing was there since Januray 3 so it couldn't cause my problem. But still the pr fixes it and to me it makes more sense.
