### ISSUE TITLE
why is that the assetcompress cannot display the compressed css correctly?

### ISSUE THREAD

**Issue by simkimsia** [markstory/asset_compress#253]
This is what gets displayed when I echo the assetcompress.

$this->AssetCompress->css('public-index.css', array('block' => 'layoutCss'));

http://example.com/cache_css/public-index.css?theme=V2Beta

Inside the response, I get <b>Warning</b> (2)</a>: file_get_contents(/var/virtual/example.com/current/src/storyzer/tmp/cache/asset_compress/public-index.css): failed to open stream: No such file or directory

My compressed files are actually like

webroot/cache_css/V2Beta-public-index.v1400332156

This is my asset_compress.ini

; Create the CSS extension
[css]
theme = true
timestamp = true
paths[] = WEBROOT/css/*
cachePath = WEBROOT/cache_css

[public-index.css]
theme = true
files[] = theme:css/common/no-banner-styles.css
files[] = theme:css/common/common.css
files[] = theme:css/common/form.css
files[] = theme:css/common/banner.css

Now using AssetCompress v0.17 because still using cakephp 2.x

**Comment by markstory** [comment]
Sounds like there is an issue with the development cache and theme files. I can look into that.

**Comment by simkimsia** [comment]
Thank you, markstory. I am still using Cake2, so will the fix work for that?

**Comment by markstory** [comment]
I can make it work :dancer:

**Comment by simkimsia** [comment]
Thank you, markstory :)

**Comment by simkimsia** [comment]
Thank you. It is working again. Cheers!~

**Comment by markstory** [comment]
Awesome, thanks for reporting the issue :smile:

**Comment by simkimsia** [comment]
Should I write a unit test for this? and if so, can give me a few clues as to how to get started?

**Comment by markstory** [comment]
I added tests in 5b0b338

**Comment by simkimsia** [comment]
Okay. Cheers. Thank you :)
