### ISSUE TITLE
Vendor namespace plugin warnings

### ISSUE THREAD

**Issue by steinkel** [markstory/asset_compress#255]
Warning (2): preg_match() [function.preg-match]: Unknown modifier 'P' [ROOT/vendor/markstory/asset_compress/src/View/Helper/AssetCompressHelper.php, line 299]
preg_match - [internal], line ??
AssetCompress\View\Helper\AssetCompressHelper::_relativizePath() - ROOT/vendor/markstory/asset_compress/src/View/Helper/AssetCompressHelper.php, line 299
AssetCompress\View\Helper\AssetCompressHelper::css() - ROOT/vendor/markstory/asset_compress/src/View/Helper/AssetCompressHelper.php, line 233
include - ROOT/templates/Layout/default.ctp, line 36
Cake\View\View::_evaluate() - CORE/src/View/View.php, line 815
Cake\View\View::_render() - CORE/src/View/View.php, line 775
Cake\View\View::renderLayout() - CORE/src/View/View.php, line 509
Cake\View\View::render() - CORE/src/View/View.php, line 471
Cake\Controller\Controller::render() - CORE/src/Controller/Controller.php, line 575
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37

The issue is related with a plugin named "Vendor/Plugin".

**Comment by markstory** [comment]
This was fixed in #254 I think.

**Comment by steinkel** [comment]
damn timezones :) sorry for adding a duplicate
