### ISSUE TITLE
Sass doesn't get regenerated when @imported (3.0)

### ISSUE THREAD

**Issue by btaens** [markstory/asset_compress#259]
When sass files that are included through @import, AssetCompress doesn't realize the file has changed.

Honestly I have no idea how you would even check for this, you'd have to basically interpret the file, and see if any imports have changed, and see if those files imported anything, and so on. It's still perfectly usable by executing *bin/cake asset_compress clear* after modifications, I just thought I'd tell you.

**Comment by markstory** [comment]
That should be working in the most recent revisions. How are you importing other files?

**Comment by btaens** [comment]
Actually, **bin/cake asset_compress build** just flat out throws an error now if run a second time.

The problem seems to be in **FreshTrait::isFresh()** which is trying to access a **_filterRegistry** property, but that never seems to be initiated, so it throws a fatal error.

**Comment by markstory** [comment]
Ok, I have a fix for that in #260

**Comment by markstory** [comment]
This should be working now. I tested similar behavior with LessPHP and LessCSS.

**Comment by CyberMonk** [comment]
Should this be working in the 2.x branch? I can't even seem to get SASS builds working without any @import lines, and @import lines are also not functioning.

**Comment by markstory** [comment]
@CyberMonk No it was only fixed in 3.x
