### ISSUE TITLE
windows path still not correct

### ISSUE THREAD

**Issue by Graziel** [markstory/asset_compress#261]
da1360cbd69a0ee039267f2467ace2854d1afaa2 still doesnt fix windows paths, there is also change needed inAssetCompressorFilter.php getName 
```
$root = str_replace('\\', '/', WWW_ROOT);
        $path = str_replace('\\', '/', $path);
        $path = str_replace($root, '', $path);
```

**Comment by markstory** [comment]
Whoops, I forgot this part.

**Comment by markstory** [comment]
Should be fixed now, sorry about that.
