### ISSUE TITLE
Feature: Extending configuration?

### ISSUE THREAD

**Issue by dereuromark** [markstory/asset_compress#263]
Would it make sense for configuration blocks to extend others?
This would often make it more DRY, 

e.g.:
```
[js-combined.js]
files[] = jquery/jquery.min.js
files[] = bootstrap/dist/js/bootstrap.min.js
files[] = anchor/anchor.js

[js-combined-extra.js]
files[] = jquery/jquery.min.js
files[] = bootstrap/dist/js/bootstrap.min.js
files[] = anchor/anchor.js
files[] = something/else.js
```

vs:
```
[js-combined.js]
files[] = jquery/jquery.min.js
files[] = bootstrap/dist/js/bootstrap.min.js
files[] = anchor/anchor.js

[js-combined-extra.js]
extend = js-combined.js
iles[] = something/else.js
```

Similar like the view block concept in CakePHP.

**Comment by markstory** [comment]
Would the extend, inherit all the configuration from the other target, or re-use the generated asset?

**Comment by dereuromark** [comment]
it might be easier to just extend the configuration. Since the script execution time is less relevant generating those again shouldn't matter really.

**Comment by markstory** [comment]
Ok, I can take a look at extending config. I've often needed that kind of thing in my work too.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
