### ISSUE TITLE
Cannot create a stylesheet tag for a build that does not exist.

### ISSUE THREAD

**Issue by alvarotrigo** [markstory/asset_compress#265]
I'm getting the following error and I have no idea why:

> Cannot create a stylesheet tag for a build that does not exist.

I'm including the helper in the App controller as I've always done:

```php
	var $helpers = array('AssetCompress.AssetCompress');
```

Then calling the combined file from the view:

```html
	echo $this->AssetCompress->css('combined');
```

I'm using a custom config with the name `asset_config_demo.ini` which I call with the `--config` option:
```
cd C:\inetpub\wwwroot\cakephp\app\
Console\cake AssetCompress.AssetCompress build_ini --config C:\inetpub\wwwroot\cakephp\app\Config\asset_compress_demo.ini
```

**Comment by markstory** [comment]
The helper will also need to know about the custom config file you're using. By default it only uses the convention based one. Currently you'd have to do this with:

```php
$this->AssetCompress->config(AssetConfig::buildFromIniFile(APP . 'Config/asset_compress_demo.ini'))
```
You might want to use a view event hook for this, or if this is too much syntax, create a pull request to make the config file a helper setting. Thus far I've only ever used the one config file though the helper so this was never implemented.

**Comment by alvarotrigo** [comment]
Thanks for it. I'll be using what you suggest.

**Comment by alvarotrigo** [comment]
How does `APP` should look like?
And...
Should I just add that line before this two lines?

```php
echo $this->AssetCompress->css('css-combined');
echo $this->AssetCompress->script('jquery-combined');
```

**Comment by markstory** [comment]
That should work.

**Comment by alvarotrigo** [comment]
Now its trying to include the files, but without the version number:

```html
<link rel="stylesheet" type="text/css" href="/tlm/css/home/css-combined.css" />

<script type="text/javascript" src="/tlm/js/home/cached/jquery-combined.js"></script>
```
Am I doing something wrong?

I'm using the following in App Controller:

```php
var $helpers = array('AssetCompress.AssetCompress');
```

And I minified them this way:

```
cd C:\inetpub\wwwroot\cakephp\app\
Console\cake AssetCompress.AssetCompress build_ini --config C:\inetpub\wwwroot\cakephp\app\Config\asset_compress_demo.ini
```

**Comment by markstory** [comment]
If you don't want the timestamps, set timestamp=false in your config file.

**Comment by alvarotrigo** [comment]
No, I want them. I just don't understand what I'm doing wrong as AssetCompress doesn't automatically add them.

**Comment by markstory** [comment]
Did the files get generated with timestamps? If the files weren't generated with timestamps you won't get timestamps in the webpage. Also timestamp files are only used if debug = 0 in your app.

**Comment by alvarotrigo** [comment]
> Did the files get generated with timestamps?

Yeah they were: `jquery-combined.v1433502723.js`

**Comment by alvarotrigo** [comment]
> Also timestamp files are only used if debug = 0 in your app.

Right. That was the problem. Thanks.
