### ISSUE TITLE
when debug set to false in cakephp 3, the cache_css fails

### ISSUE THREAD

**Issue by simkimsia** [markstory/asset_compress#268]
I am using "markstory/asset_compress": "3.0.*-dev",

with cakephp 3.x

When I set debug to false in app.php, the domain/cache_css/all.css is not found.

When I set debug back to true, the domain/cache_css/all.css is found.

Even though I did nothing in between.

Can advise?

**Comment by markstory** [comment]
When debug = false you have to build assest with the CLI tool.

**Comment by lupuswwww** [comment]
https://github.com/markstory/asset_compress/wiki/Shell
