### ISSUE TITLE
"undefined" string, issue in generated url

### ISSUE THREAD

**Issue by Pablushka** [markstory/asset_compress#271]
I'm experiencing this problem: "undefined" string issue in generated url at line 1:

`GET http://jlromero/pages/undefined?1433960846373 500 (Internal Server Error)`

The plugin works fine but this error is very annoying. The error is triggered by all views except home.

I'm using AssetCompress via composer: "markstory/asset_compress": "2.*@dev"

![image](https://cloud.githubusercontent.com/assets/1197279/8090384/08d869d6-0f84-11e5-9c38-a82a6a1fafbc.png)

I did search here and others sites for a solution, no success. Any help or suggestion is welcome.

**Comment by markstory** [comment]
Are you gluing any strings together in Javascript? PHP doesn't easily make 'undefined' however javascript can do that when you append an undefined variable into a string.

**Comment by Pablushka** [comment]
I don't think so, but I'll check it that carefully this weekend and post here any news about it. Thank you.

**Comment by markstory** [comment]
Well the string undefined does not occur in this project. So it isn't likely to have come from this code.

**Comment by Pablushka** [comment]
I',m still debugging this, please, give me a couple of days more. Thank you.

**Comment by Pablushka** [comment]
I'm sorry for the delay. I already find the problem: an old and conflicting jquery camera plugin. It has nothing to do with asset compress. I'm closing this. Thank you for your support.
