### ISSUE TITLE
Feature Request: Html minification

### ISSUE THREAD

**Issue by ADmad** [markstory/asset_compress#275]
It would be nice if AssetCompress could be used to minify response html too. I feel it's part of retuning optimized content and wouldn't be out of scope of the plugin.

**Comment by markstory** [comment]
What kind of minifications would you want to see? Is there a library we can re-use?

**Comment by ADmad** [comment]
Just basic whitespace cleanup to start with. Here are a couple of libs which looks simple enough:
https://github.com/zaininnari/html-minifier
https://github.com/WyriHaximus/HtmlCompress

**Comment by markstory** [comment]
It seems likely that compressing HTML would consume more CPU/time than send unminified HTML in quite a few cases. Are you thinking this would be done on each request?

**Comment by ADmad** [comment]
Yup it could consume noticeable amount of cpu/time. Frankly haven't thought what would be the optimal way to use it :)  It could be used on each request in combination with proper caching headers.
