### ISSUE TITLE
Timestamps not honored when `debug = true`

### ISSUE THREAD

**Issue by cwbit** [markstory/asset_compress#285]
I think it is a recognized issue? - see #220, which was for the Cake2x version but was never closed.

when `timestamp=true` in the `ini` file, and `'debug'=>true` in the `config/app.php` the AssetCompress helper only looks for the non-timestamped versions of the files. The only way to get things to work properly is to set debug to `false`.

Actually now that I've tried to regen without the timestamp it still isn't working in debug. I'm not sure if there's a file left over somewhere that is interfering?

Running the ini without the timestamp setting and the app in debug is not loading the assets for me at all. Switching debug to false works immediately.

**Comment by markstory** [comment]
Static assets are not used when debug mode is true. Generally the files are rebuilt on each request by the [dispatcher filter](https://github.com/markstory/asset_compress/blob/master/src/Routing/Filter/AssetCompressorFilter.php#L36). If the filter is not running, you won't get debug builds.

**Comment by markstory** [comment]
What does your config file look like? You can omit the asset definitions for brevity.

**Comment by markstory** [comment]
Closing as we discussed on slack and figured the solution out (plugin was not bootstrapped).

**Comment by cwbit** [comment]
OK mark helped me on this, if anyone else runs into this issue ...

Bob reads the manual. Bob calls `Plugin::load('AssetCompress', ['bootstrap'=>true]);`. Chris forgets the `bootstrap` part. Don't be like Chris. Be like Bob.
