### ISSUE TITLE
Loading layout multiple times.

### ISSUE THREAD

**Issue by aavrug** [markstory/asset_compress#287]
//error400.ctp
<?php $this->layout('default'); ?>
`<section>`
    `<div class="container">`
            `<h1>Oh, oh!</h1>`
            `<h3>Looks like you took wrong turn for 400!</h3>`
    `</div>`
`</section>`

//error500.ctp
<?php $this->layout('default'); ?>
`<section>`
    `<div class="container">`
            `<h1>Oh, oh!</h1>`
            `<h3>Looks like you took wrong turn for 500!</h3>`
   ` </div>`
`</section>`

//default.ctp
<?php echo $this->AssetCompress->script('jquery-combined'); ?>

If I am entering a wrong url getting error message from error500.ctp and loading the default layout multiple times. Once I comment the assetCompress it is working fine just load the error400.ctp file and the layout just load once.

**Comment by markstory** [comment]
I bet one of your assets has an issue, and that is causing the nested layout issues.

**Comment by aavrug** [comment]
//This is my asset_compress.ini
`[General]
cacheConfig = false

[js]
timestamp = true
paths[] = WEBROOT/*
cachePath = WEBROOT/cache_js/
filters[] = JsMinFilter

[jquery-combined.js]
files[] = js/custom.js`

// In default.ctp
`<?php //echo $this->AssetCompress->script('jquery-combined'); ?>`

I don't think there is any issue in the asset config.

**Comment by markstory** [comment]
You mentioned that the 400 error page is ok, and only the error500 page is getting a double layout. What is different about those pages that could cause a double layout? The AssetCompressHelper doesn't render a view, or layout.

**Comment by aavrug** [comment]
```
<?php $this->layout('default'); ?>
<section>
    <div class="container">
        <div class="empty-state">
            <h1>Oh, oh!</h1>
            <h3>Looks like wrong turn!</h3>
        </div>
    </div>
</section>
```

Both files having same content.

**Comment by markstory** [comment]
I'll see if I can reproduce, but the plugin code does the same thing for every asset request.

**Comment by markstory** [comment]
I wasn't able to reproduce this in an application I had, what are steps I could follow to make this error happen again?

**Comment by aavrug** [comment]
I am not sure why this is not reproducing on your code but I have tried again and getting same issue. Nothing new just with the old code which I have explained above.

**Comment by markstory** [comment]
Does your issue also happen in a new application?

**Comment by aavrug** [comment]
Yes having same issue if using same error400 and erro500 file which I have mentioned above.

**Comment by markstory** [comment]
Ok. When you're setting debug=false, have you precompiled your assets?

**Comment by aavrug** [comment]
yes

**Comment by markstory** [comment]
Ok. I'll try again on a clean app and see if I can trigger the same error.

**Comment by markstory** [comment]
I was able to reproduce this with a clean application. I'll figure out a solution in the next few days.

**Comment by markstory** [comment]
Looks like this issue stems from the `AssetCompressHelper` not being available in the error handling views. This is cause by the core `ErrorController extends Controller` and not the `AppController`.  In order to use asset compress in your error views you'll need to do:

```php
$this->loadHelper('AssetCompress.AssetCompress'); 
```

at the top of your error layout.
