### ISSUE TITLE
The requested package markstory\asset_compress could not be found

### ISSUE THREAD

**Issue by okaprinarjaya** [markstory/asset_compress#298]
←[37;41mYour requirements could not be resolved to an installable set of packages.←[39;49m

  Problem 1
    - The requested package markstory\asset_compress could not be found, it looks like its name is invalid, "\" is not allowed in package names.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

←[37;41mInstallation failed, reverting ./composer.json to its original content.←[39;49m

**Comment by markstory** [comment]
This is a temporary issue with packagist. You should try again, as there isn't anything I can do to resolve this.
