### ISSUE TITLE
Exception: Error: Unable to access jarfile

### ISSUE THREAD

**Issue by gierg** [markstory/asset_compress#301]
i got an error when i try to `php bin/cake.php AssetCompress.AssetCompress build`. always showing error like this.

`Exception: Error: Unable to access jarfile in [/Applications/MAMP/htdocs/cakephp/vendor/markstory/mini-asset/src/Filter/AssetFilter.php, line 100]
2017-05-23 04:35:23 Error: [RuntimeException] Error: Unable to access jarfile in /Applications/MAMP/htdocs/cakephp/vendor/markstory/mini-asset/src/Filter/AssetFilter.php on line 100
Stack Trace:
#0 /Applications/MAMP/htdocs/cakephp/vendor/markstory/mini-asset/src/Filter/YuiJs.php(48): MiniAsset\Filter\AssetFilter->_runCmd('java -jar "" --...', '')
#1 /Applications/MAMP/htdocs/cakephp/vendor/markstory/mini-asset/src/Filter/FilterCollection.php(66): MiniAsset\Filter\YuiJs->output('/Applications/M...', '')
#2 /Applications/MAMP/htdocs/cakephp/vendor/markstory/mini-asset/src/Output/Compiler.php(73): MiniAsset\Filter\FilterCollection->output('/Applications/M...', '')
#3 /Applications/MAMP/htdocs/cakephp/vendor/markstory/asset_compress/src/Shell/Task/AssetBuildTask.php(74): MiniAsset\Output\Compiler->generate(Object(MiniAsset\AssetTarget))
#4 /Applications/MAMP/htdocs/cakephp/vendor/markstory/asset_compress/src/Shell/Task/AssetBuildTask.php(48): AssetCompress\Shell\Task\AssetBuildTask->_buildTarget(Object(MiniAsset\AssetTarget))
#5 /Applications/MAMP/htdocs/cakephp/vendor/markstory/asset_compress/src/Shell/AssetCompressShell.php(74): AssetCompress\Shell\Task\AssetBuildTask->build()
#6 /Applications/MAMP/htdocs/cakephp/vendor/cakephp/cakephp/src/Console/Shell.php(458): AssetCompress\Shell\AssetCompressShell->build()
#7 /Applications/MAMP/htdocs/cakephp/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#8 /Applications/MAMP/htdocs/cakephp/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#9 /Applications/MAMP/htdocs/cakephp/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#10 /Applications/MAMP/htdocs/cakephp/bin/cake.php(34): Cake\Console\ShellDispatcher::run(Array)
#11 {main}`

**Comment by markstory** [comment]
Looks like you are missing a jarfile. If you want to use yuicompressor, you'll need to provide the path to the jar file.
