### ISSUE TITLE
Automatically add raw option in debug mode

### ISSUE THREAD

**Issue by savedario** [markstory/asset_compress#306]
I want my application to automatically use uncompressed/unminified assets when in debug mode.
E.g. my default layout contains:
```
	if (Configure::read('debug') > 0) {
		echo $this->AssetCompress->css('backend',['raw'=>true]);
	} else {
		echo $this->AssetCompress->css('backend');
	}
```
Maybe there's a better way to handle this..., but based on the above I thought a new 'rawOnDebug' general option in the .ini file could be used to do this test automatically inside the script() and css() methods of the helper.
I'll be happy to create a Pull Request with the changes I've made.

**Comment by markstory** [comment]
How do you see the global setting interacting with files that require pre-processing like less or sass?

**Comment by savedario** [comment]
I'm not sure I follow your reasoning.
The new option will be used only to set the existing 'raw' options automatically instead of doing it manually in the call to the helper.
The call itself will continue to do whatever is doing now when the raw=true is received.

**Comment by markstory** [comment]
> The new option will be used only to set the existing 'raw' option automatically instead of doing it manually in the call to the helper.

This is the reason for my concern. If there is a global flag/raw is enabled by default when debug is on, pre-processed CSS files will not work.

**Comment by savedario** [comment]
I use compass, so my AssetCompress deals only with .css nfiles. I will run some tests to see the implications of using the 'new' flag.

**Comment by savedario** [comment]
I can't do proper tests at the moment. I will stick with the if's in the layout for now and re-open if needed.
Thanks anyway.
