### ISSUE TITLE
2.6 (Engine: Redis) cakephp_asset_config_ts gets deleted when there are no changes

### ISSUE THREAD

**Issue by AltamashShaikh** [markstory/asset_compress#307]
Today after moving asset_compress to cache on redis, we came across a bug, when there is no changes in any files it issues a CACHE::DELETE and the keys gets deleted from redis and it serves from the last stored file, which is creating an issue since we want to use Redis only not filesystem

**Comment by markstory** [comment]
And the same delete events doesn't happen with file system caching?

**Comment by AltamashShaikh** [comment]
yes it is not getting deleted in file system
if I do a echo on delete and write method of Redis Engine following is the output

Welcome to CakePHP v2.6.8 Console
---------------------------------------------------------------
App : app
Path: /var/www/html/myblog/app/
---------------------------------------------------------------
Delete Operation
cake_cakephp_asset_config_ts
Delete Operation
cake_cakephp_asset_config_parsed
Read Operation
cake_cakephp_asset_config_parsed
Write Operation
cake_cakephp_asset_config_parsed

Building files defined in the ini file
---------------------------------------------------------------
Read Operation
cake_cakephp_asset_config_ts
Read Operation
cake_cakephp_asset_config_ts
Skip building all.v1509124368.js existing file is still fresh.
Read Operation
cake_cakephp_asset_config_ts
Read Operation
cake_cakephp_asset_config_ts
Skip building all.v1509124370.css existing file is still fresh.

Building files in views
---------------------------------------------------------------

So as we can see delete operation is being called  for both config_ts and config_parsed but post that write operation is being called only for config_parsed

**Comment by markstory** [comment]
Ok. I will see if I can reproduce locally.

**Comment by AltamashShaikh** [comment]
Yes Please

**Comment by markstory** [comment]
I've opened a pull request (#308) with a potential fix. If you could test it that would be greatly appreciated. I don't  maintain any 2.x applications anymore and am not in a good position to verify this kind of change.

**Comment by AltamashShaikh** [comment]
Will test it and update you in a while

**Comment by AltamashShaikh** [comment]
Hey, thanks the issue is resolved now (Y)

The build gives the following output when there is no change

Welcome to CakePHP v2.6.8 Console
---------------------------------------------------------------
App : app
Path: /var/www/html/myblog/app/
---------------------------------------------------------------
Read Operation
cake_cakephp_asset_config_parsed

Building files defined in the ini file
---------------------------------------------------------------
Read Operation
cake_cakephp_asset_config_ts
Read Operation
cake_cakephp_asset_config_ts
Skip building all.v1509223600.js existing file is still fresh.
Read Operation
cake_cakephp_asset_config_ts
Read Operation
cake_cakephp_asset_config_ts
Skip building all.v1509223602.css existing file is still fresh.

Building files in views
---------------------------------------------------------------

**Comment by AltamashShaikh** [comment]
Hey,

Just one suggestion can we edit the documentation for enableCache as it was
no where mentioned in the documentation that assest_compress cache config
needs to be set in core.php.

**Comment by markstory** [comment]
Sure. Would you be able to send a pull request? I don't use the 2.x version anymore.

**Comment by AltamashShaikh** [comment]
yes, will send a pull request

**Comment by markstory** [comment]
Closing as #309 and #308 have been merged.

**Comment by AltamashShaikh** [comment]
Hey,
after adding the patch, we found 1 more issue, if there is a change only in asset_compress.ini the changes do not get reflected since it gives Skip building

**Comment by markstory** [comment]
@AltamashShaikh Yes that would be a side-effect. You'll either need to clear the cache information (losing the timestamp data again) or do a full rebuild to ensure everything is built cleanly.

**Comment by AltamashShaikh** [comment]
you mean first fire the AssetCompress clear command and then AssetCompress build command ?

**Comment by markstory** [comment]
> you mean first fire the AssetCompress clear command and then AssetCompress build command ?

Yes. This will delete existing built assets though.

**Comment by AltamashShaikh** [comment]
We used —force and ol works perfectly fine :)
Thanks alot :D (Y)
