### ISSUE TITLE
Confusion about working with themes

### ISSUE THREAD

**Issue by rudy1976s** [markstory/asset_compress#312]
Hi Mark
my site is currently operating using two themes ( which are two plugins ): for the backend I have  a theme called "Backend" and for the backend one called "Backend".
I have created the ini configuration file for the backend one and put into config folder of the theme plugin.
The first think I noticed I need to reference the helper load with the plugin name otherwise it won't load the assets. ( ex $this->AssetCompress->css('Backend.all') ) .
I also created the ini for the Frontend theme and once saved  i got the following error:

Could not locate bootstrap.min.css for Backend.all.css in any configured path.

I read that configurations will merge at the very end, but I cannot really understand how to configure my themes to make it work.
Do I need to put the themes prefix when referencing assets in the ini file ? 
Could you please help me a bit ?

Thank you

Rudy

**Comment by markstory** [comment]
> Do I need to put the themes prefix when referencing assets in the ini file ?

You need to include the `theme:` prefix to indicate that a specific file is themed. And indicate that the target is themed. That is done [in the config file](https://github.com/markstory/asset_compress/wiki/Configuration#theme-assets)

>  Could you please help me a bit ?

I can't do much without knowing what your config files look like, and how you're including your assets in your views.

**Comment by rudy1976s** [comment]
Hi Mark
I have two configuration files
[Archivio.zip](https://github.com/markstory/asset_compress/files/1516099/Archivio.zip)

One is for Acm3 theme ( backend ) the other one for the frontend theme.
I am including assets in the following way:

`echo $this->AssetCompress->script('Acm3.jquery');` where jquery is the name of the group which contains the jquery assets.
Asset are stored in webroot of each theme.

Rudy

**Comment by markstory** [comment]
I will try to take a look in the next few days.
