### ISSUE TITLE
Where's value of WEBROOT const comes from?

### ISSUE THREAD

**Issue by danielfpedro** [markstory/asset_compress#315]
```javascript
[js]
cachePath = WEBROOT/cache_js/
```

I need change the value of `WEBROOT` dynamically.

**Comment by markstory** [comment]
It uses the WWW_ROOT constant defined in your application. You can see that mapping https://github.com/markstory/asset_compress/blob/cfa4de1e076f5f271cf77777e4cf854a10db7067/src/Config/ConfigFinder.php#L39
