### ISSUE TITLE
On Cakephp3.6, asset_compress generating deprecation warnings

### ISSUE THREAD

**Issue by deepak1725** [markstory/asset_compress#317]
When we tried to update our packages, we encountered deprecation warning.
![asset warn](https://user-images.githubusercontent.com/21026016/39168773-c6e4fd86-47b2-11e8-8931-7c90670bacee.png)

**Comment by markstory** [comment]
I'm planning on getting to this in the next week or so. But if you have time pull requests are always welcome.

**Comment by markstory** [comment]
Closing as a pull request is up.
