### ISSUE TITLE
Error: [Cake\Error\FatalErrorException] Call to undefined function AssetCompress\Routing\Filter\deprecationWarning()

### ISSUE THREAD

**Issue by alexdd55** [markstory/asset_compress#320]
Did an update 
`Updating markstory/asset_compress (3.2.3 => 3.3.0)`

and in production mode i get this:
`Error: [Cake\Error\FatalErrorException] Call to undefined function AssetCompress\Routing\Filter\deprecationWarning() in /Users/name/cake_project/vendor/markstory/asset_compress/src/Routing/Filter/AssetCompressorFilter.php on line 39`

everything went fine until the update and rolling it back, makes my project works again.

**Comment by markstory** [comment]
Yes. I made a mistake packaging the 3.3.0 release. Unfortunately I don't think there is a way to take that package down/away.

**Comment by alexdd55** [comment]
you could just replace the version with 3.3.1 with a fix ;)

**Comment by alexdd55** [comment]
Perfect
