### ISSUE TITLE
CSS output truncated

### ISSUE THREAD

**Issue by mnlm** [markstory/asset_compress#323]
**Info**
- AssetCompress 0.25
- LessCss filter

**Problem**
The CSS output gets truncated when building the asset files with `AssetCompress build`.

**Findings**
The generated script by the LessCss filter works fine when executed manually in the shell. The output shows the full CSS content. The issue seems to be here: https://github.com/markstory/asset_compress/blob/0.25/Lib/AssetProcess.php#L73. When debugging `$this->_output` it only has part of the actual output (65536 bytes), everything else gets cut off.

Any idea why this might be the case?

**Comment by markstory** [comment]
> Any idea why this might be the case?

No, but 65536 sounds suspiciously like a buffer length being hit somewhere.

**Comment by mnlm** [comment]
> No, but 65536 sounds suspiciously like a buffer length being hit somewhere.

Yes it does. I can't find any 64K limits in the PHP configuration so this might be either a limit in the OS somewhere (I'm using Ubuntu 18.04 LTS) or it has something to do with PHP 7.2. I tried it on Debian 8/PHP 5.6 and it works just fine.

**Comment by mnlm** [comment]
Had some time today to look into this again and it looks like nodejs might be the problem here.

If you take a generated script by the LessCss filter and run it manually `/usr/local/bin/node asset_compress_lesseitl0T` in the shell the output is complete, as already explained above.

But if you use a pipe it gets truncated. For example: `/usr/local/bin/node asset_compress_lesseitl0T | more`
This is the case for nodejs 8.11.2 LTS, as well as the latest version 10.3.0 and the current Ubuntu package version 8.10.0.

However if you switch to a really old version (0.10.29) it works just fine.

**Comment by markstory** [comment]
Sounds like something in your setup/install that will need to be figured out by you :smile:

**Comment by mnlm** [comment]
Yes, this has nothing to do with AssetCompress.
Thanks anyway!
