### ISSUE TITLE
Installation guide is outdated since 3.4.0

### ISSUE THREAD

**Issue by calcosta** [markstory/asset_compress#324]
Hi Mark,
just want to give the info that the Installation guide in the Readme file/Wiki does not work any more since version 3.4.0.
```
// in config/bootstrap.php
Plugin::load('AssetCompress', ['bootstrap' => true]);
```
should be changed to
```
// in src/Application.php
// Load AssetCompress Plugin >= 3.4.0
$this->addPlugin('AssetCompress');
```

Using the old method to load the plugin I get an error when requesting assets in debug mode.

**Comment by calcosta** [comment]
I just realized that using the new Plugin Loader via Application.php the shell command does not accept the short syntax any more.

`bin/cake asset_compress build` gives an error `Exception: Shell class for "AssetCompress" could not be found. in [/cakephp/src/Console/ShellDispatcher.php, line 327]`

`bin/cake asset_compress.asset_compress build` is still working fine.

This can be fixed if the Plugin is loaded 'the old way' via bootstrap.php in addition to the 'new way' in Application.php. But thats probably not the way to go :)

**Comment by dereuromark** [comment]
Shouldnt this be either or?
With 3.6 now the old way doesnt work anymore (no asset URLs working)

Is this now a requirement to do like this?

**Comment by markstory** [comment]
>  With 3.6 now the old way doesnt work anymore (no asset URLs working)

Are you saying that the middleware also does not work?

> What I dont get: Only issue is this plugin, for all others the former bootstrap.php loading still works and is fine.
> So this seems to create a strange and unexpected unicorn way here.

I don't fully understand the context of these statements.

**Comment by dereuromark** [comment]
Yeah, the apps then break for some reason with the old syntax (bootstrap=>true in bootstrap Plugin::load()).
So you must then use the new way as documented here. But only for this plugin.
So something is weird.

**Comment by markstory** [comment]
> So you must then use the new way as documented here. But only for this plugin. So something is weird.

The weirdness is that I removed all the files that the old plugin loading used. This problem should be resolved by cakephp/cakephp#12124. After 3.6.5 plugins using only the Plugin classes will work properly when loaded through `Plugin::load()`.

**Comment by calcosta** [comment]
This is my /src/Application.php file:
```php
class Application extends BaseApplication
{
    /**
     * Setup the middleware your application will use.
     *
     * @param \Cake\Http\MiddlewareQueue $middleware The middleware queue to setup.
     * @return \Cake\Http\MiddlewareQueue The updated middleware.
     */
    public function middleware($middleware)
    {
        $middleware
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(new ErrorHandlerMiddleware(Configure::read('Error.exceptionRenderer')))

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(new AssetMiddleware())

            // Apply routing
            ->add(new RoutingMiddleware());

        return $middleware;
    }

	/**
	 * {@inheritDoc}
	 */
	public function bootstrap()
	{
		parent::bootstrap();

		// Load Asset Compress Plugin >= 3.4.0
		$this->addPlugin('AssetCompress');
	}
}
```

In /config/bootstrap.php **I removed** `Plugin::load('AssetCompress', ['bootstrap' => true]);`

And this is what I get when executing `bin/cake asset_compress build`:
```
Exception: Shell class for "AssetCompress" could not be found. in [/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 327]
```

while `bin/cake asset_compress.asset_compress build`works fine.

**Comment by calcosta** [comment]
Yep, now it's working again. Thank you very much!
