### ISSUE TITLE
fatal error plugin class

### ISSUE THREAD

**Issue by dereuromark** [markstory/asset_compress#325]
PHP Fatal error:  Cannot use Cake\Core\Plugin as Plugin because the name is already in use in /var/www/app/vendor/markstory/asset_compress/src/AssetScanner.php on line 5

strange, this happens with "dev-master" branch.

**Comment by dereuromark** [comment]
Looks like https://github.com/markstory/asset_compress/compare/3.3.0...3.4.0#diff-f7fcf01b75ab0236c970de527853c3abR11 changes could play into this.
This happens on live deploy now.

**Comment by dereuromark** [comment]
Reverting to 3.3.1 works again - for now (using latest core package).

**Comment by dereuromark** [comment]
3.4.0 doesnt work, however. You didnt tag a release yet, though

**Comment by markstory** [comment]
There is a 3.4.1 tag which includes all changes on master.

**Comment by berarma** [comment]
I'm having the same problem. Where's the 3.4.1 tag? Do I have to switch to dev-master?

**Comment by dereuromark** [comment]
https://github.com/markstory/asset_compress/compare/3.4.0...master still missing a patch release @markstory

**Comment by markstory** [comment]
My mistake. 3.4.1 has been tagged now.

**Comment by berarma** [comment]
Thanks!
