### ISSUE TITLE
Deprecation warning - not understood

### ISSUE THREAD

**Issue by gi-jones** [markstory/asset_compress#326]
After upgrading to the latest Cakephp and setting up the plugin i Application.php, I am now getting this warning:

**Deprecated: You need to upgrade to the new Http Libraries to use AssetCompress.**
What is Http Libraries and how does one upgrade it?

**Comment by gi-jones** [comment]
Ok, seems I found the solution right after writing this. I needed to put
`parent::bootstrap();`
into the bootstrap function, but having worked from an earlier version of Cakephp/App I didn't have that.
Still not sure what Http Libraries are or do though :-)

**Comment by markstory** [comment]
https://book.cakephp.org/3.0/en/development/application.html#adding-the-new-http-stack-to-an-existing-application is the relevant docs.
