### ISSUE TITLE
Timestamp not generated for CSS

### ISSUE THREAD

**Issue by sphereweb83** [markstory/asset_compress#340]
Hello,

I am trying to use timestamps for CSS and JS files. For JS i get timestamps, but not for CSS. I am using the latest 0.26 version. Here is the output of the AssetCompress:

>Welcome to CakePHP v2.7.7 Console
>---------------------------------------------------------------
>App : app
>Path: C:\PRSVN\dev\cakephp\app\
>---------------------------------------------------------------
>
>Building files defined in the ini file
>---------------------------------------------------------------
>Saving file for allpr.v1561725767.js
>Saving file for allpr.css
>
>Building files in views
>---------------------------------------------------------------
>Skip building casual.v1561660100.js existing file is still fresh.
>

The contents of the **asset_compress_build_time** is:

> a:4:{s:8:"allpr.js";i:1561725767;s:9:"casual.js";i:1561660100;s:9:"onpage.js";i:1561649591;s:10:"~onpage.js";i:1561725403;}

The contents of the **asset_compress.ini** is:

>; Create the CSS extension
>[css]
>paths[] = WEBROOT/*
>cachePath = WEBROOT/cache_css/
>
>[allpr.css]
>timestamp = true
>files[] = css/glyphicons.css
>files[] = css/font-awesome.min.css
>files[] = css/bootstrap/bootstrap.css
>files[] = css/css.css
>filters[] = SimpleCssMin

**Comment by markstory** [comment]
Sorry, but the 2.x compatible asset compress is no longer being supported. You'll have to figure this problem out on your onw.
