### ISSUE TITLE
build command throws error with CakePHP 4.0.0

### ISSUE THREAD

**Issue by mrothauer** [markstory/asset_compress#343]
see https://travis-ci.org/foodcoopshop/foodcoopshop/jobs/629496999

`$ bin/cake asset_compress build`

Exception: Too few arguments to function Cake\Console\Shell::out(), 0 passed in /home/travis/build/foodcoopshop/foodcoopshop/vendor/markstory/asset_compress/src/Shell/AssetCompressShell.php on line 51 and at least 1 expected
In [/home/travis/build/foodcoopshop/foodcoopshop/vendor/cakephp/cakephp/src/Console/Shell.php, line 709]
2019-12-26 00:16:17 Error: [ArgumentCountError] Too few arguments to function Cake\Console\Shell::out(), 0 passed in /home/travis/build/foodcoopshop/foodcoopshop/vendor/markstory/asset_compress/src/Shell/AssetCompressShell.php on line 51 and at least 1 expected in /home/travis/build/foodcoopshop/foodcoopshop/vendor/cakephp/cakephp/src/Console/Shell.php on line 709
Stack Trace:
- /home/travis/build/foodcoopshop/foodcoopshop/vendor/markstory/asset_compress/src/Shell/AssetCompressShell.php:51
- /home/travis/build/foodcoopshop/foodcoopshop/vendor/cakephp/cakephp/src/Console/Shell.php:500
- /home/travis/build/foodcoopshop/foodcoopshop/vendor/cakephp/cakephp/src/Console/CommandRunner.php:354
- /home/travis/build/foodcoopshop/foodcoopshop/vendor/cakephp/cakephp/src/Console/CommandRunner.php:168
- /home/travis/build/foodcoopshop/foodcoopshop/bin/cake.php:12

**Comment by markstory** [comment]
Fixed in aa6cdb22fe6eeaecc0c9e27c65a5ef525efdc21d

**Comment by mrothauer** [comment]
thanks a lot!
