### ISSUE TITLE
Turbolinks : Javascript error when debug on 

### ISSUE THREAD

**Issue by r0kawa** [markstory/asset_compress#350]
`VM375 toolbar.js:71 Uncaught TypeError: Cannot read property 'postMessage' of null
    at XMLHttpRequest.<anonymous> (VM375 toolbar.js:71)
(anonymous) @ VM375 toolbar.js:71`

[full errror here] (https://gist.github.com/r0kawa/e8bc2cdf76a91c4df5463851814cbd08)

The error not happened when first loaded the page, but when navigating to different page and come back to main page, it happened.

The error gone when I make cakephp debug to off. No turbolinks code embed yet, just attach the javascript to the header.

This is my general asset_compress.ini

```
[General]
cacheConfig = false

[js]
cachePath = WEBROOT/cache_js/
paths[] = ROOT/node_modules/


[app.js]
files[] = turbolinks/dist/turbolinks.js


[css]
cachePath = WEBROOT/cache_css/
```

CakePHP version 4.0.6

**Comment by markstory** [comment]
What makes you think this error is caused by AssetCompress?

**Comment by r0kawa** [comment]
After I submit this, the more I think it’s DebugKit problem compare to AssetCompress. Can u give me confirmation that my assumption is correct ?

**Comment by markstory** [comment]
I know that there is no `toolbar.js` in AssetCompress. There is one in DebugKit but that script uses postMessage() to talk to an iframe. I've never used turbolinks but it sounds like that it is interacting poorly with how DebugKit is communicating to its iframe.
