### ISSUE TITLE
Cannot compile SVG

### ISSUE THREAD

**Issue by jiru** [markstory/asset_compress#351]
I am not sure if this is a bug or a feature request, so let me just explain my problem.

I have a lot of small SVG icons and I would like to use asset_compress to pack them into a single SVG file that I can reuse [as described here](https://css-tricks.com/svg-sprites-use-better-icon-fonts/).

I thought all I had to do was to create my own filter and to declare it in the INI file. Something like this:
```ini
[svg]
paths = WEBROOT/img/**
cachePath = WEBROOT/cache_svg/
filters[] = MySVGPackingFilter

[allicons.svg]
files[] = icons/*.svg
```

However it looks like this doesn’t work because the list of allowed extensions [is hardcoded and doesn’t include SVG](https://github.com/markstory/mini-asset/blob/a41c47c3798b8ef2fbe749b075d7b3f676e00fd0/src/AssetConfig.php#L67-L69).

Can I solve this problem without modifying asset_compress? If not, what would be the best approach to modify asset_compress so that it can do what I want?

**Comment by markstory** [comment]
I think adding svg as an extension type makes sense. If you send a pull request I can merge it and do a release.
