### ISSUE TITLE
build files

### ISSUE THREAD

**Issue by ahmedsafroot** [markstory/asset_compress#352]
when i run "bin/cake asset_compress build" this command to build css and js files i get theses errors
![Asset](https://user-images.githubusercontent.com/27191575/86775520-bcc5f880-c057-11ea-9e5c-751c76559a7b.PNG)
 
Saving file for Com2018-all-jquery-combined-defualt.v1594121531.js
Exception: Error: Unable to access jarfile in [C:\xampp\htdocs\memphis_cake3\plugins\MiniAsset\src\Filter\AssetFilter.php, line 110]
2020-07-07 11:32:11 Error: [RuntimeException] Error: Unable to access jarfile in C:\xampp\htdocs\memphis_cake3\plugins\MiniAsset\src\Filter\AssetFilter.php on line 110
Stack Trace:
#0 C:\xampp\htdocs\memphis_cake3\plugins\MiniAsset\src\Filter\YuiJs.php(47): MiniAsset\Filter\AssetFilter->_runCmd('java -jar "" --...', '/*! jQuery v1.1...')
#1 C:\xampp\htdocs\memphis_cake3\plugins\MiniAsset\src\Filter\FilterCollection.php(66): MiniAsset\Filter\YuiJs->output('C:\\xampp\\htdocs...', '/*! jQuery v1.1...')
#2 C:\xampp\htdocs\memphis_cake3\plugins\MiniAsset\src\Output\Compiler.php(72): MiniAsset\Filter\FilterCollection->output('C:\\xampp\\htdocs...', '/*! jQuery v1.1...')
#3 C:\xampp\htdocs\memphis_cake3\plugins\AssetCompress\src\Shell\Task\AssetBuildTask.php(74): MiniAsset\Output\Compiler->generate(Object(MiniAsset\AssetTarget))
#4 C:\xampp\htdocs\memphis_cake3\plugins\AssetCompress\src\Shell\Task\AssetBuildTask.php(42): AssetCompress\Shell\Task\AssetBuildTask->_buildTarget(Object(MiniAsset\AssetTarget))
#5 C:\xampp\htdocs\memphis_cake3\plugins\AssetCompress\src\Shell\AssetCompressShell.php(74): AssetCompress\Shell\Task\AssetBuildTask->build()
#6 C:\xampp\htdocs\memphis_cake3\vendor\cakephp\cakephp\src\Console\Shell.php(517): AssetCompress\Shell\AssetCompressShell->build()
#7 C:\xampp\htdocs\memphis_cake3\vendor\cakephp\cakephp\src\Console\CommandRunner.php(385): Cake\Console\Shell->runCommand(Array, true)
#8 C:\xampp\htdocs\memphis_cake3\vendor\cakephp\cakephp\src\Console\CommandRunner.php(162): Cake\Console\CommandRunner->runShell(Object(AssetCompress\Shell\AssetCompressShell), Array)
#9 C:\xampp\htdocs\memphis_cake3\bin\cake.php(12): Cake\Console\CommandRunner->run(Array)
#10 {main}

**Comment by markstory** [comment]
Sounds like you're missing a jarfile for yuijs. I don't include one with assetcompress. You'll need to download it separately and configure the filter to have the path to the yui compressor jar file. The [configuration docs](https://github.com/markstory/asset_compress/wiki/Configuration) have an example of how to do that.

**Comment by ahmedsafroot** [comment]
hello markstory, i can't find a jarfile online so please get me a link to download and tell me where i can put it. thanks

**Comment by ahmedsafroot** [comment]
@markstory  . i put this lines in configuration file 
[filter_YuiJsFilter]
path = /webphonepro/yuicompressor-2.4.7.jar
and the "yuicompressor-2.4.7.jar" there inside webphonepro folder which in webroot folder but i still get same issues. please advise and thanks

**Comment by ahmedsafroot** [comment]
Dear @markstory  , i find the issue but i can't know why this happen ?! . in the YuiJs class and YuiCss Class the default path you write in vendor directory but when but yuicompressor.jar inside yuicompressor directory inside vendor directory not work but when change 
protected $_settings = array(
        'path' => 'yuicompressor/yuicompressor.jar'
    );
to full path this work 
protected $_settings = array(
        'path' => 'C:\xampp\htdocs\memphis_cake3\vendor\yuicompressor/yuicompressor.jar'
    );

**Comment by markstory** [comment]
Sounds like you may have a CWD related issue. Using the full path is generally a better idea anyways. You can use file path constants in your configuration file as well so you don't have to put environment specific paths in your configuration file.

I'm going to close this as it seems like you figured out your problem with the configuration paths.
