### ISSUE TITLE
matthiasmullie/minify Filter

### ISSUE THREAD

**Issue by umer936** [markstory/asset_compress#368]
A more regularly updated filter with support for both JS and CSS would be nice, especially without dependencies like Ruby or Java. 

https://github.com/matthiasmullie/minify seems to fit the bill. 

I'm thinking I'll make a PR adding this filter in the future.

**Comment by markstory** [comment]
Sounds good to me. I'm open to deprecating tools that are no longer actively used as well.

**Comment by berarma** [comment]
This filter is already included along with others, but the docs are very outdated. 

They're also duplicated here and in the mini-asset wiki which is the tool really doing the work, asset_compress is now just a wrapper around it.

I think we should remove the documentation about filters here and direct to the documentation in mini-asset and update the info there.

The new filters are:

- ClosureCompiler (the service it relies on has been deprecated)
- CssCompressor
- Hogan
- ImportInline
- JShrink
- JSqueeze
- LessDotPHP
- Minify
- PipeInput
- PipeOutput
- ScssPHP
- SimpleCssMin
- TimestampImage
- TypeScript

Filters that use seemingly  abandoned software and thus should be deprecated:

- YuiCss
- YuiJs
- CssMinFilter
- LessPHP
- JsMinFilter

**Comment by markstory** [comment]
Updated the docs for both projects. Thanks for the nudge @berarma
