### ISSUE TITLE
Callback function not being called

### ISSUE THREAD

**Issue by umer936** [markstory/asset_compress#369]
I'm attempting to use a callback to be able to use a variable for the theme. 

My goal is to be able to set the `themes[]` from .env by reading it in a PHP file (for now I'm just doing `Application::getTheme()`).

However, copy/pasting the method described in the docs ( https://github.com/markstory/asset_compress/wiki/Configuration#callback-files ) 

gives me:
`syntax error, unexpected '(' in /web/merit/config/asset_compress.ini on line 61`

Is this still doable? Or am I missing something else?

**Comment by markstory** [comment]
Have you tried quoting the value? It should be there in the docs as well.
