### ISSUE TITLE
sprite support

### ISSUE THREAD

**Issue by dereuromark** [markstory/asset_compress#85]
I can see AssetCompress supporting sprite generation for css icons etc.
There are usually dozens to hundreds of small images embedded via css - probably mainly as background-image.
Not sure if that's outside the scope of this plugin. But combining those hundreds of files in a single sprite and adding the x,y coordinates to the css on output would dramatically reduce file hits on the system.

**Comment by dereuromark** [comment]
With sophisticated tools like http://compass-style.org/help/tutorials/spriting/ it is probably best to use those instead - and since AssetCompress can work with SASS, this should be easy.

**Comment by markstory** [comment]
Agreed :+1:
